package com.example.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class CT02ValidarCriticaCamposObrigatoriosTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    String pathDriver = "C:\\Selenium\\chromedriver.exe"; 
    
    @Before
    public void setUp() {
        //setup do googlechrome
        System.setProperty("webdriver.chrome.driver", pathDriver);
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void cT02ValidarCriticaCamposObrigatorios() {
        // Test name: CT02ValidarCriticaCamposObrigatorios
        // Step # | name | target | value
        // 2 | open | /contato | 
        driver.get("https://livros.inoveteste.com.br/contato");
        // 4 | click | css=.wpcf7-submit | 
        driver.findElement(By.cssSelector(".wpcf7-submit")).click();
        // 5 | pause | 10000 | 
        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 7 | assertText | css=.your-name > .wpcf7-not-valid-tip | O campo é obrigatório.
        assertThat(driver.findElement(By.cssSelector(".your-name > .wpcf7-not-valid-tip")).getText(), is("O campo é obrigatório."));
        // 8 | assertText | css=.your-email > .wpcf7-not-valid-tip | O campo é obrigatório.
        assertThat(driver.findElement(By.cssSelector(".your-email > .wpcf7-not-valid-tip")).getText(), is("O campo é obrigatório."));
        // 9 | assertText | css=.your-subject > .wpcf7-not-valid-tip | O campo é obrigatório.
        assertThat(driver.findElement(By.cssSelector(".your-subject > .wpcf7-not-valid-tip")).getText(), is("O campo é obrigatório."));
        // 10 | assertText | css=.your-message > .wpcf7-not-valid-tip | O campo é obrigatório.
        assertThat(driver.findElement(By.cssSelector(".your-message > .wpcf7-not-valid-tip")).getText(), is("O campo é obrigatório."));
        // 11 | close |  | 
        driver.close();
    }
}
