package com.example.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class CT03EnviarMenssagemTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    String pathDriver = "C:\\Selenium\\chromedriver.exe"; 

    @Before
    public void setUp() {
        //setup do googlechrome
        System.setProperty("webdriver.chrome.driver", pathDriver);
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void cT03EnviarMenssagem() {
        // Test name: CT03EnviarMenssagem
        // Step # | name | target | value
        // 2 | open | /contato | 
        driver.get("https://livros.inoveteste.com.br/contato");
        // 4 | click | name=your-name | 
        driver.findElement(By.name("your-name")).click();
        // 5 | type | name=your-name | Luis Fellipe
        driver.findElement(By.name("your-name")).sendKeys("Luis Fellipe");
        // 6 | click | name=your-email | 
        driver.findElement(By.name("your-email")).click();
        // 7 | type | name=your-email | luis.fellipe1217@gmail.com
        driver.findElement(By.name("your-email")).sendKeys("luis.fellipe1217@gmail.com");
        // 8 | click | name=your-subject | 
        driver.findElement(By.name("your-subject")).click();
        // 9 | type | name=your-subject | Curso gratuito de Selenium
        driver.findElement(By.name("your-subject")).sendKeys("Curso gratuito de Selenium");
        // 10 | click | name=your-message | 
        driver.findElement(By.name("your-message")).click();
        // 11 | type | name=your-message | Quais são os módulos desse curso?
        driver.findElement(By.name("your-message")).sendKeys("Quais são os módulos desse curso?");
        // 13 | click | css=.wpcf7-submit | 
        driver.findElement(By.cssSelector(".wpcf7-submit")).click();
        // 14 | pause | 10000 | 
        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 16 | assertText | css=.wpcf7-response-output | Agradecemos a sua mensagem. Responderemos em breve.
        assertThat(driver.findElement(By.cssSelector(".wpcf7-response-output")).getText(), is("Agradecemos a sua mensagem. Responderemos em breve."));
    }
}
